name: document_scanner_kit_ios
description: iOS implementation of the document_scanner_kit plugin
version: 0.1.0+1
repository: https://github.com/AhmetSBulbul/document_scanner_kit/tree/main/document_scanner_kit_ios

environment:
  sdk: ^3.4.0
  flutter: '>=3.0.0'

flutter:
  plugin:
    implements: document_scanner_kit
    platforms:
      ios:
        pluginClass: DocumentScannerKitPlugin
        dartPluginClass: DocumentScannerKitIOS

dependencies:
  flutter:
    sdk: flutter
  document_scanner_kit_platform_interface: ^0.1.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  plugin_platform_interface: ^2.1.8
  very_good_analysis: ^6.0.0
