version: 2
enable-beta-ecosystems: true
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/document_scanner_kit"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/document_scanner_kit/example"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/document_scanner_kit_platform_interface"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/document_scanner_kit_android"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/document_scanner_kit_ios"
    schedule:
      interval: "daily"