name: document_scanner_kit_platform_interface
description: A common platform interface for the document_scanner_kit plugin.
version: 0.1.0+1
repository: https://github.com/AhmetSBulbul/document_scanner_kit/document_scanner_kit_platform_interface

environment:
  sdk: ^3.4.0

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^6.0.0
